spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/spendly
    username: spendly
    password: spendly_dev

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080